### ISSUE TITLE
Problem with new monogame

### ISSUE THREAD

**Issue by KakCAT** [craftworkgames/FarseerPhysics.Portable#4]
Hi @craftworkgames ,

I'm using Farseer with monogame for a Windows 8.1 game. Everything's been fine so far, but a few days ago I updated monogame.

Right now I'm getting the following error:

System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework, Version=3.1.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The bound assembly has a version that is lower than that of the request. (Exception from HRESULT: 0x80132000)
   at Game.FarseerHelper.init()
....

It seems like monogame version is tied to farseer, and monogame version was upgraded. What is the easiest way to fix this?  (I suppose I have a generate again a PCL version of monogame and then use that reference and recompile, but I have no idea how to generate a PCL version of monogame (I can't find any solution generated in protobuild which seems a PCL version)

thanks!

**Comment by craftworkgames** [comment]
Hi @KakCAT 

Yes, you're right. The MonoGame version is tied to Farseer. This is an unfortunate design flaw in the way MonoGame works because they haven't split MonoGame up into several different libraries like XNA used to be. This makes it very difficult to build MonoGame extensions like Farseer without the need to recompile it for every supported platform.

This issue has been [discussed before](https://github.com/mono/MonoGame/issues/2500) but the issue was closed without a resolution.

@DDReaper has done a lot of work in the area of making MonoGame work as a PCL and I believe he is the current maintainer of the PCL fork and would be the person to talk to about this.

It looks like [another discussion](https://github.com/mono/MonoGame/issues/3405) about MonoGame PCL has come up in recent times. I've only just discovered it so I don't really know much about what's going on.

This issue bothered me so much that I created [my own game framework](http://astrid.craftworkgames.com/) that doesn't use MonoGame at all. Of course, it's mostly just me working on it so it's not nearly as complete as MonoGame. It's what I use for my own game dev these days though.

To answer you're question more specifically; to fix the issue with the Farseer PCL you'd need to recompile it against a new version of the MonoGame PCL. This process shouldn't be *too* complicated if @DDReaper has maintained his PCL NuGet package I wouldn't think.

**Comment by KakCAT** [comment]
Hi @craftworkgames ,

thanks, I understand and I see your point. Honestly sometimes I'm a bit lost with monogame, being a gameplay programmer used to watch only my own code, touching code that has been modified by hundreds of programmers makes me dizzy :) so I'm unable to see the scope of making MonoGame PCL compliant.

I found a workaround though :)

I just modified MonoGame's version before compiling.  Moved MonoGame manually from 3.3 to 3.1.2 and recompiled. So far it seems farseer works as it did before, and monogame version AFAIK does mean nothing but to have a reference.

I suppose if MonoGame was heavily rewritten this would not work, but as most "important" parts are quite stable and 99% of changes today are for content pipeline or fixing problems in several platform-specific areas, this should be enough to keep going for some time :)

**Comment by craftworkgames** [comment]
Nice work. Yes, the actual MonoGame code that Farseer uses is only a few primitive type classes like Vector2, Vector3, etc. So what you did should be fine.

It's funny, I'm pretty good with making game frameworks but gameplay programming is something I still struggle with. If you ever want to help me that I'd be interested to learn from you.

**Comment by KakCAT** [comment]
haha, I wish I knew enough :) I tried a long time ago with some friends but
I failed miserably. I started at 10, self-taught, and this is usually a bad
recipe for teaching :)

2015-04-23 11:32 GMT+02:00 Dylan Wilson <notifications@github.com>:

**Comment by craftworkgames** [comment]
No matter. Talk to you later.
